### ISSUE TITLE
АШЫПКА АШЫПКА АШЫПКА АШЫПКА АШЫПКА АШЫПКА 

### ISSUE THREAD

**Issue by gentoocat** [p1xeldust/pako#31]
ГДЕ КОММЕНТАРИИ В КОДЕ АШЫПКА АШЫПКА АШЫПКА АШЫПКА 
Я НИЧЕГО НЕ ПОНИМАТЬ
ЧИНИТЬ ВАШ КОД
АШЫПКА АШЫПКА

**Comment by p1xeldust** [comment]
Поправим комментарии, спасибо за замечание.
